server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/menu?autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true
    username: postgres
    password: Joy123
  jpa:
    default:
      properties:
        hibernate:
          physical_naming_strategy: "io.micronaut.data.hibernate.naming.DefaultPhysicalNamingStrategy"
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update

  cors:
    allowed-origins: http://localhost:3000
  mail:
    host: smtp.gmail.com
    port: 587
    username: jyoshnaguravana@gmail.com
    password: gjjq ygha ucra ekuu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true